version: 2
updates:

  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    commit-message:
      prefix: fix
    directory: "/"
    schedule:
      interval: "weekly"
