backend:
  name: git-gateway
  branch: main

site_url: https://www.walchenseehaus.de
locale: de
media_folder: "src/images"
public_folder: "src/images"

collections:
  - name: page
    label: Seiten
    label_singular: Seite
    folder: "src/pages/"
    slug: "{{slug}}"
    create: false
    delete: false
    editor:
      preview: false
    fields:
      - { label: Layout, name: layout, widget: hidden, default: page }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }

  - name: hinweis
    label: Hinweis
    delete: false
    editor:
      preview: false
    files:
      - name: buchung
        label: Buchungs-Hinweis
        file: "src/content/booking/hint.md"
        fields:
          - { label: Active, name: active, widget: boolean, default: false }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown, modes: ["raw"] }
